import React, { useState } from 'react';
import { GitPullRequest, Copy, Check, Ticket, ExternalLink, HelpCircle } from 'lucide-react';

export default function DiffViewer({ diff, filename, onOpenPR, onOpenTicket }) {
  const [copied, setCopied] = useState(false);
  const [prUrl, setPrUrl] = useState('');
  const [prLoading, setPrLoading] = useState(false);
  const [ticketUrl, setTicketUrl] = useState('');
  const [ticketLoading, setTicketLoading] = useState(false);

  if (!diff) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(diff);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCreatePR = async () => {
    setPrLoading(true);
    try {
      const response = await fetch('http://localhost:3001/api/github/pr', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          filename,
          patch: diff,
          title: `fix(security): remediate vulnerabilities in ${filename}`,
          body: `## Vulnerability Fix Patch\nAutomatically generated by Code Guardian Agent Swarm.\n\n### Changes:\n- Replaced insecure interfaces with secure patterns.`
        })
      });
      const data = await response.json();
      if (data.prUrl) {
        setPrUrl(data.prUrl);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setPrLoading(false);
    }
  };

  const handleCreateTicket = async () => {
    setTicketLoading(true);
    try {
      const response = await fetch('http://localhost:3001/api/linear/issue', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: `Remediate security vulnerability in ${filename}`,
          description: `The Code Guardian security audit has proposed a patch to fix critical vulnerabilities detected in ${filename}. Please review and merge.`
        })
      });
      const data = await response.json();
      if (data.issueUrl) {
        setTicketUrl(data.issueUrl);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setTicketLoading(false);
    }
  };

  const lines = diff.split('\n');

  return (
    <div className="glass-card" style={{ marginTop: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <h2 style={{ fontSize: '15px', fontWeight: '700' }}>Remediation Patch Diff</h2>
        <div style={{ display: 'flex', gap: '8px' }}>
          <button className="btn btn-secondary" style={{ padding: '6px 12px', fontSize: '12.5px' }} onClick={handleCopy}>
            {copied ? <Check size={14} style={{ color: 'hsl(var(--success))' }} /> : <Copy size={14} />}
            {copied ? 'Copied' : 'Copy Patch'}
          </button>
        </div>
      </div>

      <div className="diff-container">
        {lines.map((line, idx) => {
          let typeClass = '';
          if (line.startsWith('+') && !line.startsWith('+++')) typeClass = 'added';
          else if (line.startsWith('-') && !line.startsWith('---')) typeClass = 'removed';
          else if (line.startsWith('@') || line.startsWith('diff') || line.startsWith('---') || line.startsWith('+++')) typeClass = 'header';

          return (
            <div key={idx} className={`diff-line ${typeClass}`}>
              {line || ' '}
            </div>
          );
        })}
      </div>

      {/* Integrations Section */}
      <div style={{
        marginTop: '20px',
        paddingTop: '20px',
        borderTop: '1px solid hsl(var(--border))',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: '12px'
      }}>
        <div>
          <h4 style={{ fontSize: '13px', fontWeight: '600' }}>Swarm Integration Actions</h4>
          <p style={{ fontSize: '11px', color: 'hsl(var(--text-muted))' }}>Deploy changes immediately to GitHub repository or Linear board via Composio.</p>
        </div>

        <div style={{ display: 'flex', gap: '12px' }}>
          {prUrl ? (
            <a href={prUrl} target="_blank" rel="noopener noreferrer" className="btn btn-accent" style={{ fontSize: '12px', padding: '8px 16px' }}>
              View Pull Request <ExternalLink size={12} />
            </a>
          ) : (
            <button 
              className="btn btn-primary" 
              style={{ fontSize: '12px', padding: '8px 16px' }}
              onClick={handleCreatePR}
              disabled={prLoading}
            >
              <GitPullRequest size={14} /> {prLoading ? 'Creating PR...' : 'Create GitHub PR'}
            </button>
          )}

          {ticketUrl ? (
            <a href={ticketUrl} target="_blank" rel="noopener noreferrer" className="btn btn-secondary" style={{ fontSize: '12px', padding: '8px 16px', borderColor: 'hsl(var(--secondary))', color: 'hsl(var(--secondary))' }}>
              View Ticket <ExternalLink size={12} />
            </a>
          ) : (
            <button 
              className="btn btn-secondary" 
              style={{ fontSize: '12px', padding: '8px 16px' }}
              onClick={handleCreateTicket}
              disabled={ticketLoading}
            >
              <Ticket size={14} /> {ticketLoading ? 'Opening Ticket...' : 'Open Linear Ticket'}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
